name: Fan_Sports
description: FSC is an icon of Fan Sports Club where players participate in different type of games like Tennis, Badminton, Table tennis, Squash from distant places. Using the FSC app players will be updated about national, international, club level tournaments with more number of players as participants performing on the grounds and simultaneously involving the senior players of the nation who sometimes think of their retirement from the sports. Using the FSC app we facilitate people to easily login for the tournaments, know the whereabouts of the events happening in India and abroad with a single click on their Andriod or iOS devices. A player can have the entire information about his individual profile, national and international rank, events being held globally and the destination tourneys  organized time to time by the tennis fraternity. A player looking for a doubles partner, information about the tournaments held nearby, the fee structure and facilities provided, all this can be visualized by a single click at FSC.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.2+19




environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_linkify: ^1.1.1
  url_launcher: 
  flutter_calendar: ^0.0.8
  flutter_signin_button: ^0.2.6
  scoped_model: ^1.0.1
  http:
  flutter_datetime_picker: ^1.1.6
  splashscreen:
  material_design_icons_flutter: ^3.2.3595
  flutter_picker: ^1.0.10
  dynamic_theme: ^1.0.0

  flutter:
    sdk: flutter
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/logo-fansport.png
    - assets/logo-fsc.png
    - assets/logoITF.jpg
    - assets/playerBackground.jpg
    - assets/tournamentInfo.jpg 
    - assets/profilePicture.jpeg
    - assets/splashScreen.jpg
    - assets/itf-card.jpg
    - assets/about-cover.jpg

  
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
